### ISSUE TITLE
How to download bundle if I wasn't logged in when I purchased? 

### ISSUE THREAD

**Issue by lestephane** [xtream1101/humblebundle-downloader#19]
When I purchased a bundle, i only provided an email address.
So I received a link by email to download the bundle without the intermediate login step.
When I run 

```bash
hbd gen-cookies --cookie-file hbd-cookies.txt
``` 

Then paste the email link in the browser location bar, nothing happens, the chrome browser instance does not get closed, despite seemingly having all the required cookies set.

Has anyone managed to successfully download an 'anonymous' bundle (one purchased without a login).

**Comment by azuravian** [comment]
I believe an "anonymous" bundle still shows up under your login if you use the same email address.  If you have an account under that email address, log in and see if that bundle shows up under your purchases.

**Comment by lestephane** [comment]
I claimed the bundle using an existing account I had. Then I was able to download using the cookie from a session established with that existing account. case closed.
