### ISSUE TITLE
Dowload fails since upgrading to the newest version

### ISSUE THREAD

**Issue by Akashic101** [xtream1101/humblebundle-downloader#20]
```
C:\Users\David>hbd download --cookie-file hbd-cookies.txt --library-path K:\Humble_Bundle --progress
Traceback (most recent call last):
  File "C:\Python27\Scripts\hbd-script.py", line 11, in <module>
    load_entry_point('humblebundle-downloader==0.2.2', 'console_scripts', 'hbd')()
  File "c:\python27\lib\site-packages\humblebundle_downloader\cli.py", line 97, in cli
    from .download_library import DownloadLibrary
  File "c:\python27\lib\site-packages\humblebundle_downloader\download_library.py", line 338
    ), end='\r')
          ^
SyntaxError: invalid syntax
```

**Comment by xtream1101** [comment]
You must use python 3, not python 2

**Comment by Akashic101** [comment]
Using python3 it know throws another error: 
![py_VfCYR0QjOh](https://user-images.githubusercontent.com/39961794/76702548-e33bde80-66ca-11ea-8285-cc8c87c69e38.png)

**Comment by xtream1101** [comment]
You run that command just in your terminal, not in a python shell

**Comment by rytilahti** [comment]
Btw, if you want, you could add [`python_requires`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) to your `setup()` to make pip enforce the python version requirement :-)

**Comment by leptoid** [comment]
I just ran it and it is working fine for me.  Been running all night.
