### ISSUE TITLE
"--trove" don't work for some games

### ISSUE THREAD

**Issue by tl-pierre** [xtream1101/humblebundle-downloader#23]
Hi ! 
First, thank you for this great script ! I just used it to download the Humble Trove and I noticed that the script doesn't try to download certain games. I tried to restart the script several times which allowed me to download some missing games, but for the list below, nothing helps. The script doesn't want to download them. I don't see any error messages, it just doesn't seem to detect them.

Tested on Manjaro Linux, 11/04/2020 : 
```
- Trine Enchanted Edition
- Deadlight
- The Penumbra Collection
- Amnesia: A Machine for Pigs
- The Bridge
- ETHEREAL
- SanctuaryRPG: Black Edition
- A Short Hike
- FOTONICA
- MirrorMoon EP
- Once Upon A Crime In The West
- macdows 95
- Broken Sword: Director's Cut
- Anna's Quest
- Broken Sword 2 - the Smoking Mirror
- Chaos on Deponia
- DON'T GIVE UP
- Blackguards
- Roman Sands
- Dear Esther
```

I also noticed an another problem: when the script has finished downloading the Humble Trove, it then tries to download the rest of the purchases made on Humble Bundle.

:)

**Comment by xtream1101** [comment]
I created a new issue for the `--trove` flag downloading everything here https://github.com/xtream1101/humblebundle-downloader/issues/24 

As for the issue of it missing some games, I will have to dig into that issue.
Are you using any filtering flags with your command?

**Comment by xtream1101** [comment]
So for the games that are not downloading, it looks like they are Steam games. This script cannot download them since all you get is the steam key that you then use to activate it. There is nothing to download through the Humble Bundle site itself.

**Comment by tl-pierre** [comment]
Hi,
The game list I have made is for Humble Trove games only : it seems to me they all are DRM-free games and there's no Steam keys.
For exemple, Trine Enchanted Edition is one of the missing games and if I try to download it manually, I see that there is 3 files available [on the Trove website](https://www.humblebundle.com/subscription/trove?selected=trine_enhanced_trove) :
```
trine_enchanted_edition_v2_12_build_508_humble_linux_full.zip
trine_enchanted_edition_v2_12_build_508_humble_osx_full.zip
trine_enchanted_edition_v2_12_build_510_humble_windows_full.zip
```
To answer your question, I don't use any filtrer.

Thank you !

**Comment by Jimmyson** [comment]
Running the latest version of this, it also failed to grab the games list in the initial ticket.
I had a look over the JSON blob of one of the faulting games, compared to a successfully downloaded game. I noticed that the payload structure differs. There is few points of data, in particular it is missing the "uploaded_date" value that the program is looking for

https://github.com/xtream1101/humblebundle-downloader/blob/f0dbf79ae05598a926673266ac83113d43ae8b55/humblebundle_downloader/download_library.py#L104

I'm not familiar with Python, so I don't know if its throwing exceptions, or bailing out of the function, and preventing the download from occurring.

[trove-blackguard-blob.zip](https://github.com/xtream1101/humblebundle-downloader/files/4626737/trove-blackguard-blob.zip)

**Comment by xtream1101** [comment]
@Jimmyson Thanks for the json data. Its not that the `uploaded_at` key is missing because that is allowed to be, it will fallback to using only the md5 key. I will look deeper into this.

**Comment by TheFrenchGhosty** [comment]
@xtream1101 I can confirm that this bug is still a thing, out of the 93 games currently available (yes I counted), it only downloads 77.

This is a massive issue in my opinion.

**Comment by matega** [comment]
The issue is caused by Humble not including `uploaded_at` values with every game. Because this, both the "cached" value and the retrieved value for `uploaded_at` will be `None` on line 126, so the program believes that a file with this `uploaded-at` date has already been downloaded.

https://github.com/xtream1101/humblebundle-downloader/blob/d0d93d194970391a83779c8446592090e1e32dd4/humblebundle_downloader/download_library.py#L126-L127

I've added some fallbacks so it always gets a somewhat appropriate value that is not `None`.
