### ISSUE TITLE
Linked Chrome plugin does not supply working cookie

### ISSUE THREAD

**Issue by SagaciousZed** [xtream1101/humblebundle-downloader#27]
The linked Chrome plugin does supply a cookie file that can be used with hbd. Comparing the output of the two linked plugins, I got found that while the plugin exports in the correct Netscape structure it is improperly escaping the values. see https://github.com/daftano/cookies.txt/issues/1

Chrome 83 on Windows 10

**Comment by ajshell1** [comment]
I can confirm the same issue with Chromium 83 for (Arch) Linux.

**Comment by xtream1101** [comment]
This extension is working for me on Mac with Chrome 84. I do see how this could be an issue though. If anyone finds a better extension I will update the readme with it.

**Comment by Showerrodney** [comment]
Had the same issue with the Chrime plugin. Had to trial a good number of extensions until I found one that exported a working .txt file with everything properly escaped:

"Get cookies.txt" https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid/related

Of course, I cannot vouch for this extension in any capacity other than its ability to export a compliant Netscape cookie file.

**Comment by xtream1101** [comment]
Cookie info updated in version 0.3.3
