### ISSUE TITLE
Humble Trove URL returning HTTP 400

### ISSUE THREAD

**Issue by Jimmyson** [xtream1101/humblebundle-downloader#28]
In an effort to get the latest Trove games from my subscription, the Trove URL has been updated to throw 400 errors without the full parameters.

https://github.com/xtream1101/humblebundle-downloader/blob/8561180f3f5ead0be555cd1d4c204b53b27c97bd/humblebundle_downloader/download_library.py#L166

The URL now needs the parameters "**property**" and "**direction**".

**Example**
```
https://www.humblebundle.com/api/v1/trove/chunk?property=popularity&direction=desc&index=0
```

**Comment by bradgy** [comment]
Thanks @Jimmyson , replacing the URL with 

`https://www.humblebundle.com/api/v1/trove/chunk?property=popularity&direction=desc&index={idx}`

worked for me.

For anyone else, I had to look in python3.8/site-packages/humblebundle_downloader to find download_library.py, That directory for my was inside the lib folder in my virtualenv - if you are installing systemwide that directory will be somewhere else for you.

**Comment by xtream1101** [comment]
@Jimmyson Thank you for finding this fix. I have updated the code so the newest version should now work.
