### ISSUE TITLE
Failed to get list of purchases

### ISSUE THREAD

**Issue by WhaleJ84** [xtream1101/humblebundle-downloader#30]
As using the recommended Firefox extension didn't work (see issue #29), using the Cookie Quick Manager extension worked enough to move the program to the next stage.
Now, the only output I am getting is: `Failed to get list of purchases` with no extra output to determine what is going wrong.
Is there some sort of way I could go about debugging this?

**Comment by xtream1101** [comment]
That means it is not even able to request the page `https://www.humblebundle.com/home/library`. I updated that log line to display the error it is running into, will be available in the next version later today. It will give a better idea on whats going on.
