### ISSUE TITLE
`hbd --help` does not show available options

### ISSUE THREAD

**Issue by rayanth** [xtream1101/humblebundle-downloader#38]
Running `hbd -h` or `hbd --help` doesn't show all available options (with which to get more detailed help on how to use them or what they're for). It only shows:
```
usage: hbd [-h] {download} ...

positional arguments:
  {download}
    download  Download content in your humble bundle library

optional arguments:
  -h, --help  show this help message and exit
  ```

Expected: a list of available options, as with most CLI's.
Version: 0.3.4, installed from `pip install humblebundle-downloader`

Without any more info from `hbd --help`, one must inspect source to see what options there are...

**Comment by xtream1101** [comment]
The newest update has this change. 
When this script first came out it had a few different actions it could do, but they have been removed and the "download" is all that remained. You can still pass `download` as the first argument, but now it will log a deprecation warning and run as expected to keep backwards compatibility.
