### ISSUE TITLE
Missing Downloads - maybe because of the /

### ISSUE THREAD

**Issue by masterdot** [xtream1101/humblebundle-downloader#49]
No url found: Humble PC Android Bundle 12/Costume Quest
No url found: Humble Bundle - PC and Android 8/Jack Lumber
No url found: Humble Bundle - PC and Android 8/AaaaaAAaaaAAAaaAAAAaAAAAA for the Awesome
No url found: Humble Botanicula Debut/Kooky
No url found: Humble Botanicula Debut/Kooky
No url found: Humble Botanicula Debut/Kooky
No url found: Humble Mo-boo-ile Bundle/The Spookening
No url found: Humble Mo-boo-ile Bundle/The Spookening
No url found: Humble Mo-boo-ile Bundle/The Spookening
No url found: Humble Mo-boo-ile Bundle/The Spookening
No url found: Humble eBook Bundle/Signal to Noise
No url found: Humble Indie Bundle 2/Osmos
No url found: Humble Indie Bundle 6/Dustforce DX
No url found: Humble Indie Bundle 7/Indie Game - The Movie
No url found: Humble Indie Bundle 9/FTL - Faster than Light
No url found: Humble Mobile Bundle 7/Horn
No url found: Humble Mobile Bundle 8/TowerMadness 2
No url found: Humble Weekly Bundle - Presented by Rock Paper Shotgun/World Of Goo Soundtrack

This are the bundles that are not downloaded. Maybe its because of the / in the name. The rest works perfectly, thanks for the awesome script!

**Comment by warthog9** [comment]
So I ran into this too and started looking at it.  Something on the download page doesn't return a downloadable link, and thus the "no url found", however the way this bails isn't that it stops for that product it cycles to the next item and keeps looking.  I believe this is LIKELY an ignorable warning, though you should double check those.  I don't believe this actually needs to be resolved (though maybe the message could be improved some?)

**Comment by larryhastings** [comment]
I spent some time investigating this.  tl;dr: you can ignore it, and it would probably be better if the tool didn't print the error message.

First of all, the slash has nothing to do with it.  It's added as part of the error message:

    logger.info("No url found: {bundle_title}/{product_title}" [...]

It's not part of the product name, it's not confusing the tool internally.  That's not what's going on.

Here's what's going on.  For every "product", the tool downloads a blob of JSON information.  That blob includes a list of downloadable things called the "download_struct".  Most of the time, the entries on that list identify an individual file the tool can download--its URL, its MD5 and SHA1 checksums, a timestamp, and its size in both human-readable and machine-readable forms.  But sometimes one of these entries will contain other stuff that has nothing to do with directly downloading a file.  For example:

* "World Of Goo Soundtrack" has an entry linking to [a web page](https://kylegabler.com/WorldOfGooSoundtrack/) where you can download the soundtrack for free.
* "Dustforce" has some sort of list of ".js" and ".ogg" files in an "asm_manifest"--maybe a Javascript soundtrack player?
* "Costume Quest" has an entry linking to [a web page](https://support.humblebundle.com/hc/en-us/articles/204372938) explaining which APK you should select for side-loading.
 
Every one of these I've looked at has legitimately been something the tool can safely ignore.  And in particular, every one has had a "human_size" set to "0 bytes", which seems like a hint in the JSON that there's nothing for the tool to download from this entry.  Also, in every case, I found that the product that displayed this error message _did_ download the product.  For example, I got this error for both "Dustforce" and "Costume Quest", yet both products downloaded fine.

I'm going to submit a PR suppressing this error message when the "human_size" is "0 bytes".  But for now I believe you can safely ignore these warnings.

**Comment by xtream1101** [comment]
This should fix a handful of these https://github.com/xtream1101/humblebundle-downloader/pull/75. If anything still needs fixing then please open a new issue so we can resolve that specific issue.
