### ISSUE TITLE
Program keeps overwriting already downloaded files

### ISSUE THREAD

**Issue by Akashic101** [xtream1101/humblebundle-downloader#5]
When using
`hbd --progress`

I noticed that it continues downloading 1epub, 1.cbz and 1.pdf and continues to overwrite those files as seen here: https://i.imgur.com/saHpqIx.png and this is the download-location: https://i.imgur.com/oDYfBWn.png

**Comment by Silvenga** [comment]
I can confirm this, for example,

Shelter 2 has three downloads:

```
Downloading: Shelter 2.zip: 100% [==================================================]
Downloading: Shelter 2.zip: 100% [==================================================]
Downloading: Shelter 2.zip: 100% [==================================================]
```

And comparing this against Humble Bundle:

![image](https://user-images.githubusercontent.com/2753330/72695965-1cf3cd00-3b00-11ea-8e74-4cbbd83fb195.png)

There are three platforms, each one with a different zip file.

It appears that `hbd` is overriding duplicate downloads.

**Comment by Silvenga** [comment]
This appears to be actually very common:

![image](https://user-images.githubusercontent.com/2753330/72696259-292c5a00-3b01-11ea-9b75-5215623bc2d1.png)

**Comment by xtream1101** [comment]
Ah, I have not seen this yet. I will find something that does this and seems the best thing to do will be to name it like:
`Shelter 2 [Mac].zip`
`Shelter 2 [Linux].zip`
`Shelter 2 [Windows].zip`

Would that work for everyone?

**Comment by azuravian** [comment]
Another related issue is with PDFs and HD PDFs.  I am currently limiting to specific filetypes and downloading epub, pdf, and cbz.  For PDFs, it downloads both the HD and the standard PDF and names them the same, therefore overwriting the HD version with the standard version.

**Comment by tjwlucas** [comment]
Also the same with audio Zips (e.g. FLAC/mp3)

**Comment by xtream1101** [comment]
Ok, so since there are so many different cases, it seems the best option is to have the original download name be used for the actual file. I realized that this will not be to bad since all the files are still grouped under the same folder which has a nice human readable name.
