### ISSUE TITLE
Haven't been able to use this since HB redid the trove setup

### ISSUE THREAD

**Issue by odd-function** [xtream1101/humblebundle-downloader#63]
I setup hbd earlier this year and had it running for a while, but shortly after the change, the trove was no longer downloadable (might be permanent given the client). Worse though, is that I haven't been able to use this at all. No matter if I'm providing the cookie via argument or file, whether I'm asking to download by key or platform it keeps crashing and suggesting that I'm not including a cookie. I've made the suggested change to line 174 (new link for JSON data), but this hasn't resolved my issue.

**Comment by hardpenguin** [comment]
This looks like the most recent fork, maybe try this one? https://github.com/matega/humblebundle-downloader

I am also looking for solution and just found this link but I cannot try it out at the moment :)

**Comment by SteffanLong** [comment]
That fork and associated PR #59 resolved the Humble Trove issue for me.

**Comment by odd-function** [comment]
> That fork and associated PR #59 resolved the Humble Trove issue for me.

Thanks for the suggestions from both of you. I've deleted the jail that I run this in and recreated it, but the issue is sticking around. It is still insisting that I'm not including the cookie (the trove issue just being the first part that failed).

**Comment by xtream1101** [comment]
This issue thread should help with any cookie issues https://github.com/xtream1101/humblebundle-downloader/issues/50. Closing this issue as https://github.com/xtream1101/humblebundle-downloader/pull/59 seems to solve the original problem
