### ISSUE TITLE
"Unable to download user-data", something changed in HB?

### ISSUE THREAD

**Issue by Job76** [xtream1101/humblebundle-downloader#66]
Hi,
This downloader is fantastic, but I seem to have some trouble lately. I suspect that something might have changed on Humble Bundle? I have tried this from two pc's (both win 10) and both have worked in the past. Now I get the same error on both machines. 
```
Traceback (most recent call last):
  File "C:\Python\Python39-64\Scripts\hbd-script.py", line 33, in <module>
    sys.exit(load_entry_point('humblebundle-downloader==0.4.0', 'console_scripts', 'hbd')())
  File "C:\Python\Python39-64\lib\site-packages\humblebundle_downloader\cli.py", line 84, in cli
    DownloadLibrary(
  File "C:\Python\Python39-64\lib\site-packages\humblebundle_downloader\download_library.py", line 63, in start
    self.purchase_keys = self.purchase_keys if self.purchase_keys else self._get_purchase_keys()  # noqa: E501
  File "C:\Python\Python39-64\lib\site-packages\humblebundle_downloader\download_library.py", line 397, in _get_purchase_keys
    raise Exception("Unable to download user-data, cookies missing?")
Exception: Unable to download user-data, cookies missing?
```

I do not know what the exact fault is, but line 397 is the following:
```
user_data = library_page.css('#user-home-json-data').xpath('string()').extract_first()  # noqa: E501
if user_data is None:
      raise Exception("Unable to download user-data, cookies missing?")
```

Is the library_page.css file part of the webpage? and is that missing?  I am sure that I have given the cookie string correctly as it has worked before, and I have even tried and replaced it with a new string that I got in the same way as the first that was working.
To fix this is way above my skill level, so I hope that you can fix it soon. Many thanks!

**Comment by darylf** [comment]
I'm getting this error as well. I didn't bother reading the error message and only saw the "cookies missing?" text and tried updating my cookie, but it still fails for me.

**Comment by darylf** [comment]
Although my problem might have been unrelated from Op's, I reinstalled `humblebundle-downloader`, updated my cookie, and it works for me now.

**Comment by kivikant** [comment]
Go with browser to https://www.humblebundle.com/home/library and it probably asks you to login. 
After that you get the correct session from the cookie and you're able to use the downloader. I had the same issue with a new computer.
