### ISSUE TITLE
Support Using Original File Names

### ISSUE THREAD

**Issue by Silvenga** [xtream1101/humblebundle-downloader#9]
Given the bundle `Humble Survive This Bundle`, for the game `Shelter 2`, three zips can be downloaded:

![image](https://user-images.githubusercontent.com/2753330/72696117-ad321200-3b00-11ea-9fc3-06ace0a989f9.png)

```
https://dl.humble.com/OSX_Shelter2_Build20150708.zip
https://dl.humble.com/Linux_Shelter2_Build20150708.zip
https://dl.humble.com/PC_Shelter2_Build20150708.zip
```

However, `hbd` appears to use the game name `Shelter 2.zip` instead for the resulting download file.

`hbd` should attempt to maintain the original file name, this would also resolve #5.

**Comment by xtream1101** [comment]
The reason I choose not to use the original file names is most of the times they are not very human friendly when browsing. For example a lot of ebook titles are all just a single word not broken up which makes them hard to read.
I posted in #5 about a possible solution.
